# Generated by Django 4.1.3 on 2022-11-30 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leagues", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PlayerStatistics",
            new_name="PlayerGameStatistics",
        ),
        migrations.AlterModelTable(
            name="playergamestatistics",
            table="player_game_statistics",
        ),
    ]
